#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          alsa-audio-pipe
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      udev alsa-utils hostname
# Should-Stop:       udev alsa-utils
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Piping audio from one ALSA device to another.
# Description:       Piping audio from one ALSA device to another.
### END INIT INFO


PATH=/sbin:/bin:/usr/sbin:/usr/bin

DAEMON=/home/pi/alsa-audio-pipe/alsa_audio_piper.py
DAEMONUSER=pi

PIDDIR=/var/run/alsa_audio_piper
PIDFILE=$PIDDIR/pid

INPUT_DEVICE=system
OUTPUT_DEVICE=SoundSticks
FLOOR_NOISE=128

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

alsa_audio_pipe_start () {
	log_daemon_msg "Starting alsa-audio-pipe"
	if [ ! -d $PIDDIR ]; then
	    mkdir -p $PIDDIR
	    chown $DAEMONUSER:$DAEMONUSER $PIDDIR
	fi
	start-stop-daemon -m -b -c $DAEMONUSER -p $PIDFILE -x $DAEMON --start -- --input $INPUT_DEVICE --output $OUTPUT_DEVICE --floor-noise $FLOOR_NOISE
	status=$?
	log_end_msg ${status}
}

alsa_audio_pipe_stop () {
	log_daemon_msg "Stopping alsa-audio-pipe"
	start-stop-daemon -p $PIDFILE --stop --retry 5 || echo -n "...which is not running"
	log_end_msg $?
}

case "$1" in
	start|stop)
		alsa_audio_pipe_${1}
		;;
	restart|reload|force-reload)
  	alsa_audio_pipe_stop
		alsa_audio_pipe_start
		;;
	force-stop)
		alsa_audio_pipe_stop
		kill $(cat $PIDFILE) || true
		sleep 2
		killall -9 $(cat $PIDFILE) || true
		;;
	status)
		status_of_proc -p $PIDFILE "$DAEMON" "alsa-audio-pipe" && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/alsa-audio-pipe {start|stop|force-stop|restart|reload|force-reload|status}"
		exit 1
		;;
esac

exit 0
