#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          alsa-audio-pipe
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Should-Start:      udev alsa-utils hostname
# Should-Stop:       udev alsa-utils
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Piping audio from one ALSA device to another.
# Description:       Piping audio from one ALSA device to another.
### END INIT INFO

DAEMON=/home/pi/alsa_audio_pipe/alsa-audio-pipe.sh
PIDDIR=/var/run/alsa-audio-pipe
PIDFILE=$PIDDIR/pid
PATH=/sbin:/bin:/usr/sbin:/usr/bin

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

alsa_audio_pipe_start () {
	log_daemon_msg "Starting alsa-audio-pipe daemon"
	if [ ! -d $PIDDIR ]; then
		mkdir -p $PIDDIR
	fi
	start-stop-daemon -n aplay -x $DAEMON --start -b
	status=$?
	log_end_msg ${status}
}

alsa_audio_pipe_stop () {
	log_daemon_msg "Stopping alsa-audio-pipe daemon"
	start-stop-daemon -n aplay --stop --retry 5 || echo -n "...which is not running"
	log_end_msg $?
}

case "$1" in
	start|stop)
		alsa_audio_pipe_${1}
		;;
	restart|reload|force-reload)
		if [ -s $PIDFILE ] && kill -0 $(cat $PIDFILE) >/dev/null 2>&1; then
			alsa_audio_pipe_stop
			alsa_audio_pipe_start
		fi
		;;
	force-stop)
		alsa_audio_pipe_stop
		killall aplay || true
		sleep 2
		killall -9 aplay || true
		;;
	status)
		status_of_proc -p $PIDFILE "$DAEMON" "alsa-audio-pipe daemon" && exit 0 || exit $?
		;;
	*)
		echo "Usage: /etc/init.d/alsa-audio-pipe {start|stop|force-stop|restart|reload|force-reload|status}"
		exit 1
		;;
esac

exit 0
